name: Azure VM Update Workflow

on:
  push:
    branches:
      - main

jobs:
  update-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure VM Update
        run: |
          az vm extension set \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --vm-name ${{ secrets.VM_NAME }} \
            --name CustomScript \
            --force-update \
            --publisher Microsoft.Azure.Extensions \
            --settings '{"fileUris": []}' \
            --protected-settings '{"commandToExecute": "export GITHUB_TOKEN=${{ secrets.TOKEN }} && sudo -u azureuser bash /home/azureuser/SDA_Project/update_app.sh"}'
